### ISSUE TITLE
Run `composer dump-autoload -o` in deployment

### ISSUE THREAD

**Issue by Jeroenll** [davidalger/capistrano-magento2#102]
As stated in the [deployment flow](https://devdocs.magento.com/guides/v2.2/performance-best-practices/deployment-flow.html) we should run `composer dump-autoload -o` after `bin/magento setup:di:compile`.

Is it possible to add this in a new version?

**Comment by davidalger** [comment]
@JeroenVanLeusden Thanks for the request. I honestly didn't even know they recommended that (it certainly wasn't there when 2.0 came out!) but it totally makes sense given what DI compilation is doing.

Working on putting together v0.8.0 which will have this as well as support for zero-down deploys per #34 I'll be publishing this very soon!

**Comment by hostep** [comment]
Hi folks!

Has this been tested? Because I just did that, and there is 0 difference in the autoload files (`vendor/composer/autoload_*.php`) generated before or after running `setup:di:compile`.
If I search for this, I can find this StackExchange answer, which confirms my findings: https://magento.stackexchange.com/q/202071/2911

So it feels like this optimisation has no use and will only slow down the deployments slightly.

However, if you change your `composer.json` file as follows (based on Magento 2.1.12, 2.2.x is slightly different):
```diff
➜ git diff composer.json
diff --git a/composer.json b/composer.json
index 14212c7a..bd0ef403 100644
--- a/composer.json
+++ b/composer.json
@@ -60,7 +60,10 @@
             "Magento\\": "app/code/Magento/"
         },
         "psr-0": {
-            "": "app/code/"
+            "": [
+                "app/code/",
+                "var/generation/"
+            ]
         },
         "files": [
             "app/etc/NonComposerComponentRegistration.php"
```

Then it actually makes a difference and a lot more lines are added to the autoload files.

Shouldn't this extra line in the `composer.json` file be added to the M2 codebase by default?
I haven't tested what this would mean for local development, if this would create annoying behavior or not (probably not, but untested).

Thoughts?

Thanks!

**Comment by QuentinFarizon** [comment]
I agree with @hostep, this is necessary  ! This is tested and in production for us.

Moreover, a much greater improvement is using the --apcu option of dump-autoload (https://getcomposer.org/doc/articles/autoloader-optimization.md#optimization-level-2-b-apcu-cache)
I you have ACPU extension installed on your server, you will see huge performance improvements (250ms gain on each server call for us). If you don't have ACPU installed, it does nothing and it's harmless.
With this, every file path for each class will be cached, and absolutely no unecessary file looking is done.

For these reasons, I think this should be the default along with --optimize option.

PR opened on devdocs : https://github.com/magento/devdocs/pull/2115

**Comment by jpratt** [comment]
Please include this PR. Make sure those that are not using composer during deploy are not breaking: https://github.com/davidalger/capistrano-magento2/pull/106

**Comment by davidalger** [comment]
Thanks guys for chasing this down to have the core include what's necessary for the optimization to work! Since that's now been merged into core M2 and the flag already implemented here, I'm going to go ahead and close this out again. Cheers!
