### ISSUE TITLE
Nothing present for Optimization Level 2/B : APCu Cache

### ISSUE THREAD

**Issue by bera9605** [davidalger/capistrano-magento2#112]
https://github.com/davidalger/capistrano-magento2/blob/master/lib/capistrano/tasks/magento.rake

In file ^ at row 113 we have --optimize-autoloader which is like running -o ( ref: https://devdocs.magento.com/guides/v2.0/config-guide/prod/prod_perf-optimize.html#server---composer-optimization ) 

So i propose the add the flag --apcu-autoloader to the composer install call ( ref : https://getcomposer.org/doc/articles/autoloader-optimization.md#optimization-level-2-b-apcu-cache )

**Comment by davidalger** [comment]
@bera9605 The gem does support the use of the native php-opcache extension as well as provides means to flush the opcache on each deployment to avoid it being filled as a result of repeated atomic deployments:
https://github.com/davidalger/capistrano-magento2#php-opcache-reset

APCu on PHP 7 is not something I have plans to support. You're welcome to fork and/or override those rake routines to do this on your own, or you could simply add the following to your project's composer.json as outlined by the above docs page you linked to:

> Set "apcu-autoloader": true inside the config key of composer.json

**Comment by erikhansen** [comment]
@davidalger Thanks for your `apcu-autoloader` suggestion. I've added that to the the `composer.json` file of a recent M2 project and it's generating an APCU-optimized autoloader, as expected.

```json5
{
    "name": "magento/project-community-edition",
    …
    "config": {
        …
        "apcu-autoloader": true
    },
```

For the the record: updated link to the relevant [DevDocs article](https://devdocs.magento.com/guides/v2.3/performance-best-practices/deployment-flow.html#preprocess-dependency-injection-instructions) recommend APCU, since the one from the OP is no longer valid.

**Comment by erikhansen** [comment]
UPDATE: I was wrong—the error I ran into below was not directly related to the APCU cache, despite the initial false positives I got when troubleshooting. So ignore my comment below.

Leaving this here in case it's helpful to anyone who may run into a similar issue:

I enabled `apcu-autoloader` a while back and I've twice run into an issue caused by it.

There were a couple of times where the `magento:setup:db:data:upgrade` resulted in an error after a new extension was installed, as presumably Magento couldn't find the newly created class files. I was able to consistently reproduce this error until I implemented the fix I mention below.

```
Running /usr/bin/env php -f bin/magento -- setup:db-data:upgrade as deploy@example.com
       Data install/update:
       Module 'Magento_Store':
       Module 'Magento_AdvancedPricingImportExport':
       ...
       Module 'Aheadworks_Layerednav':
       PHP Fatal error:  Uncaught Error: Call to undefined method Aheadworks\Layerednav\Api\Data\FilterExtension::getFilterMode() in /srv/www/magento-dev/releases/20191220040546/vendor/aheadworks/module-layered-navigation/Model/ResourceModel/Filter/Relation/Mode/SaveHandler.php:93
Stack trace:
#0 /srv/www/magento-dev/releases/20191220040546/vendor/aheadworks/module-layered-navigation/Model/ResourceModel/Filter/Relation/Mode/SaveHandler.php(60): Aheadworks\Layerednav\Model\ResourceModel\Filter\Relation\Mode\SaveHandler->getModesDataToSave(Object(Aheadworks\Layerednav\Model\Filter))
#1 /srv/www/magento-dev/releases/20191220040546/vendor/magento/framework/EntityManager/Operation/Create/CreateExtensions.php(48): Aheadworks\Layerednav\Model\ResourceModel\Filter\Relation\Mode\SaveHandler->execute(Object(Aheadworks\Layerednav\Model\Filter), Array)
#2 /srv/www/magento-dev/releases/20191220040546/vendor/magento/framework/EntityManager/Operation/Create.php(122): Magento\Framework\EntityManager\Operation\Create\CreateExtensions->execute(Object( in /srv/www/magento-dev/releases/20191220040546/vendor/aheadworks/module-layered-navigation/Model/ResourceModel/Filter/Relation/Mode/SaveHandler.php on line 93
```

I believe this happens with "extension attribute" classes since Magento will have already generated a different version of the class before the new extension is installed.

My solution to this issue was to update my `tools/cap/lib/capistrano/tasks/flush_apcu_cache.rake` file to flush the APCU cache before the `magento:setup:db:schema:upgrade` command runs (in addition to after each deployment, which I already had in place):

```
# Prevent errors when extensions add "Extension Attribute" information
before "magento:setup:db:data:upgrade", "cachetool:apcu:clear:first" do
  on release_roles :all do
    within release_path do
      execute :cachetool, 'apcu:cache:info'
      execute :cachetool, 'apcu:cache:clear'
    end
  end
end

# Ensure APCU cache is cleared to prevent using outdated cache information
after "deploy:published", "cachetool:apcu:clear:second" do
  on release_roles :all do
    within release_path do
      execute :cachetool, 'apcu:cache:info'
      execute :cachetool, 'apcu:cache:clear'
    end
  end
end
```
