### ISSUE TITLE
/app/etc/config.php check on deployment?

### ISSUE THREAD

**Issue by cscd98** [davidalger/capistrano-magento2#122]
My app/etc/config.php is part of my repo, yet it thinks current and release are different?

```
01:26 magento:maintenance:check
      Checking database status...
      Declarative Schema is not up to date
      Data patches are not up to date
      
      
      Checking config status...
      <release_path>/app/etc/config.php hash: 18c27bca9f82a820c70e3f885695dcd5
      <current_path>/app/etc/config.php hash: n/a
      Maintenance mode will not be disabled (config hashes differ).
```

This is causing setup:db-schema:upgrade and setup:db-data:upgrade to run, even when I don't need it to.

I don't want any upgrades to take place, as I haven't installed Magento yet

**Comment by cscd98** [comment]
Maybe this instead https://github.com/davidalger/capistrano-magento2/issues/116

**Comment by davidalger** [comment]
The check to this file is done because it is one of the indicators that setup upgrade should be run on deployment, in this case as the `current_path` value shows `n/a` it's evident this is the first deployment. 

For the first deployment, the tool expects that you already have a database setup and a working env.php file in place with proper connection details to connect to that database. I.e. the gem does not handle `setup:install` and expects you have already done so and set things up accordingly.

There may be a few things in this post that are out of date, but this initialization process is outlined in this guest blog over on my site:
https://davidalger.com/posts/deploying-magento2-using-capistrano/
