### ISSUE TITLE
Skip invoke 'magento:composer:install'?

### ISSUE THREAD

**Issue by cscd98** [davidalger/capistrano-magento2#13]
I use jenkins to do my deployments and it already has downloaded all composer modules before it goes off to deploy to my sites.

So it's not necessary to run invoke magento:composer:install.

I've tried copying deploy.rake to lib/capistrano/tasks/deploy.rake and commented out the above call, however it still seems to run the magento:composer:install

**Comment by davidalger** [comment]
@craigcarnell Interesting scenario to bring this up! Do you think this is a scenario which will be commonly run into by folks using a CI / CD pipeline?

You should be able to override that file, but will need to make sure the one from the gem isn't loaded since Capistrano / Rake DSL works by adding to vs replacing existing task declarations (resulting in one running after the other.

To do this, you'll want to replace this in your `Capfile`:

``` ruby
require 'capistrano/magento2/deploy'
```

with the following two lines:

``` ruby
require 'capistrano/deploy'
require 'capistrano/magento2'
```

This will allow your `deploy.rake` to replace the one included with the gem, while still using the calls defined in `magento.rake`.

**Comment by cscd98** [comment]
@davidalger Thanks that worked for me!

**Comment by craigcarnell** [comment]
@davidalger would it be possible to make this a setting? so I keep my file up to date with yours and any further changes?

Also is it possible to skip maintenance mode? This causes an exception for me due to a bug in data migration tool

**Comment by davidalger** [comment]
For future reference, see issue #15 as well.
