### ISSUE TITLE
Maintenance mode alert

### ISSUE THREAD

**Issue by valguss** [davidalger/capistrano-magento2#137]
Some of my colleagues would like to see a yes/no confirmation ideally at the beginning of a deployment if maintenance mode will need to be invoked and if so, is that OK

IE, if you select Y then deployment continues as normal
If you select N, then deployment quits

This would be so that we can inform the client that their site will be in maintenance mode for a couple of minutes for the deployment

This feature should also be enabled via configuration

Cheers

Tom

**Comment by davidalger** [comment]
> yes/no confirmation ideally at the beginning of a deployment if maintenance mode will need to be invoked

This is unfortunately not very feasible. As can be seen from the capistrano output when running a deploy, the maintenance mode checks occur after the application code is build almost immediately prior to when maintenance would start. The reason being the app has to be built in the release directory and ready to rock-n-roll in order to compare it with the versions found in the database.

What I generally do is review release PRs for modules with version changes (or new modules) and config.php changes that would trigger app:config:import requirement. Could even automate this sort of check in CI and have it require an extra approval step on the PR if need be (this is what I'd suggest actually)

It would be possible to implement a yes/no prompt when the checks is run, most of the way through the deploy, just not at the beginning before it starts (not something I'd like to support in the gem natively however). If you want to do this for your project, see here for an example of how to add custom invocation (there is also a good lot on this in Capistrano documentation):
https://github.com/davidalger/capistrano-magento2/issues/133#issuecomment-574787843

Example of how to do a yes/no prompt can be found here:
https://github.com/davidalger/capistrano-magento2/blob/master/lib/capistrano/tasks/pending.rake#L33-L39

**Comment by valguss** [comment]
Thanks @davidalger . I'll look into the PR approval step. I happen to think you're right in that you should already know if it's going to produce a maintenance page, but I told my colleagues i'd ask the question :)

Cheers
