### ISSUE TITLE
Version dependencies for capistrano

### ISSUE THREAD

**Issue by PascalBrouwers** [davidalger/capistrano-magento2#144]
Could we have the version dependencies for capistrano back to ~3.1 ?
I'd like to keep using capistrano 3.6

Are there any features of capistrano being used to requires capistrano 3.14?

**Comment by davidalger** [comment]
@PascalBrouwers Probably going to leave it as-is unfortunately, unless there is a really good reason to keep supporting the older versions of Capistrano. I realize this means you'll either need to stick with 0.8.9 version of this gem or use the newer version of Capistrano. The gem is now using the `invoke!` method, which didn't exist until Capistrano 3.9, so that use would have to be reverted in order to support the older version.

Out of curiosity, are you running into a major hiccup trying to use 3.14? Ruby version issues perhaps?

Version 3.1 is from mid 2016, so it's getting up there in age, but IIRC the only thing required to move from 3.1 to 3.7 is  to include the following in the project `Capfile` to account for the new SCM setup under the hood:

```
# Load Git plugin
require 'capistrano/scm/git'
install_plugin Capistrano::SCM::Git
```

I recently took all my current projects from using capistrano 3.9 to capistrano 3.14.0 and 3.14.1 without any issues nor changes required, so I'm going to guess that going from 3.1 to 3.14.1 would be similar with the exception of the above, given the SCM changes rolled out in 3.7.

**Comment by PascalBrouwers** [comment]
Ah, you're using `invoke!` then I'll have to upgrade. The issue is that I'm using a git strategy which is not compatible with capistrano 3.7+. I'll see if I can get it working for capistrano 3.14 then.

**Comment by PascalBrouwers** [comment]
Yep, got it to work by overriding the `git:create_release` task. Eg:
```
class Capistrano::SCM::Git::WithSubmodules < Capistrano::SCM::Git
  Rake::Task["git:create_release"].clear_actions

  def define_tasks
    task "git:create_release" do
      # my own implementation
      end
    end
end
```

**Comment by davidalger** [comment]
@PascalBrouwers Glad you found a working solution. Appreciate you sharing it here.

Another fairly common git deployment strategy is for deploying a sub-tree from the repo, such as when Magento lives in `./webroot` vs in the repo root. I've used this one quite a lot myself, I think it was Capistrano 3.3 which added the `:repo_tree` setting:

```
set :repo_tree, 'webroot' # relative path to project root in repo
```

Just posted it here for completeness in case anyone else stumbles across this issue, but there is also a gem for implementing a sub-modules strategy (I have not used it, just know it exists): https://github.com/ekho/capistrano-git-submodule-strategy

**Comment by PascalBrouwers** [comment]
Yeah, I like to have a git clone in the release folder so I can easily identify locally changes files, etc.
Let me share that part of the script here:
```
    task "git:create_release" do
      on release_roles :all do
          execute :mkdir, "-p", release_path
          execute :git, "clone", repo_path, release_path
          execute <<-EOCOMMAND
            cd #{release_path} && git checkout #{fetch(:branch)} && git remote set-url origin #{repo_url} && git submodule update --init --recursive
          EOCOMMAND
      end
    end
```

I now https://github.com/ekho/capistrano-git-submodule-strategy does the git submodules a liitle bit more elegant but this script is already fine for me.
