### ISSUE TITLE
Change deployment order of DI compile and schema upgrade

### ISSUE THREAD

**Issue by bjarn** [davidalger/capistrano-magento2#154]
We're currently experiencing issues with a couple of modules, i.e. Wyomind's Framework module. In order to maintain backwards compatibility, they copy files based on the Magento version during the recurring schema scripts.

However, currently the capistrano tasks first execute `setup:di:compile` and then run `db:schema:upgrade`.

Since this is causing issues, we looked up the Magento devdocs and they also suggest to first run setup upgrade (or in this case `db:schema:upgrade`) and then execute `setup:di:compile`:
https://devdocs.magento.com/guides/v2.4/config-guide/deployment/single-machine.html

Therefore I believe the order should be changed so the issues mentioned above can be resolved.

**Comment by PascalBrouwers** [comment]
Not sure if this always goes correct if there is a Factory of Proxy class in the schema upgrade. Though I've never seen this before or tested it.

**Comment by davidalger** [comment]
I've worked around this issue with Wyomind code by putting the following in the `composer.json` of a project with their CronScheduler module:

```
    "scripts": {
        "pre-autoload-dump": [
            "rm -vf vendor/wyomind/cronscheduler/Plugin/Cron/Observer/ProcessCronQueueObserver_2.*.php"
        ]
    },
```

The order here cannot be changed, and doing so because Wyomind did something that essentially breaks the ability to build and deploy separately isn't something I would consider.
