### ISSUE TITLE
Customize magento core location

### ISSUE THREAD

**Issue by amansilla** [davidalger/capistrano-magento2#17]
After a try I faced that this just supose that magento is installed in the `root` folder of the repository cloned but in my case magento is installed in the `src` folder of my repository. 

Do you now if there is a light way e.g. setting a variable to customize where the magento is located?

Thanks you.

**Comment by erikhansen** [comment]
@amansilla A quick Google search turned up the following (from [here](http://stackoverflow.com/a/21344915/2726785)):

> As of Capistrano 3.1, you can now use the :repo_tree configuration variable, which makes this answer obsolete. For example:
> 
> ```
> set :repo_url, 'https://example.com/your_repo.git'
> set :repo_tree, 'relative/path/from/your/repo' # relative path to project root in repo
> ```
> 
> See http://capistranorb.com/documentation/getting-started/configuration.

Let me know if that works for you.

**Comment by amansilla** [comment]
@erikhansen :+1: great job, with the following config got it working as desired:

`set :repo_tree, 'src'`

Thank you for this tipp, I guess you can close the issue.

**Comment by davidalger** [comment]
Thanks @erikhansen for chiming in. That's a great solution when it's desirable to only deploy a portion of the repository. Additionally, it's possible to also simply configure one's virtual host to point at the proper location in `<deploy_dir>/current/src/pub` instead of `<deploy_dir>/current/pub`. Closing.
