### ISSUE TITLE
HTTPS on

### ISSUE THREAD

**Issue by clicktrend** [davidalger/capistrano-magento2#21]
Hi,

due to my server configuration I need to run this static-content:deploy command:

```
HTTPS=on php bin/magento setup:static-content:deploy en_US
```

This creates static files in "secure" directory. To deploy this with capistrano I created this task

```
desc "Deploy static files"
task :static_deploy do
    on roles(:app) do
        within release_path do
            execute "cd '#{release_path}' && HTTPS=on php bin/magento setup:static-content:deploy en_US"
        end
    end
end
```

Is it possible to pass "HTTPS=on" in your script?

**Comment by davidalger** [comment]
@clicktrend Based on my checking, the only additional files created by running the tool with HTTPS=on are secure versions of the requirejs-config.js files. To this end, I've implemented it so that in Magento 2.1, the new options in the tool will be taken advantage of to speed things up, while still allowing the command to generate both non-secure and secure versions of the files.

This work was done in commit 8881466 and 1ccc7c4.

If this does not accomplish what you need, please let me know!

**Comment by davidalger** [comment]
Note: This will be included in the next tagged release, which I plan on tagging shortly. :)

**Comment by hostep** [comment]
Let's cross reference this issue with the corresponding issue in Magento2: https://github.com/magento/magento2/issues/4961

**Comment by davidalger** [comment]
Good call, @hostep!
