### ISSUE TITLE
magento:cache:varnish:ban command fails silently

### ISSUE THREAD

**Issue by erikhansen** [davidalger/capistrano-magento2#3]
If the `:ban_pools` and `:varnish_cache_hosts` values are set in the configuration files, the `magento:cache:varnish:ban` command should fail if Varnish doesn't return a "200 Purged" message. This will ensure that a user won't mistakenly think that Varnish purging is working.

**Comment by davidalger** [comment]
The command reveals the output of the curl call (response from varnish from called) whether it is an error message or a success message. 200 Purged is merely a synthetic reply from the VCL file, which does not actually indicate success, but rather is only a reply from varnish to avoid it passing on the request to the application.

I don't think this command should hard-fail a deploy by default. What happens if the `:varnish_cache_hosts` is set to an invalid IP? Wouldn't the curl exit code fail the build? I.e. I'm assuming the only soft-fail would be when its successfully connecting to varnish, but due to a mis-configuration of the VCL file the effect isn't one of purging anything from the cache.

**Comment by erikhansen** [comment]
You make good points. Hard-failing a deploy is probably too drastic. 

Unless you customize the Magento VCL to modify the synthetic reply to a different message, you can reasonably assume that a "200 Purged" response means the Varnish purge was successful. And as a result of that, I think it at least makes sense to output an error when a "200 Purged" response is not received. But I'll leave that up to you to decide and am closing this issue.
