### ISSUE TITLE
Deploy fails when pub/media contains a large number of files

### ISSUE THREAD

**Issue by erikhansen** [davidalger/capistrano-magento2#31]
I'm getting this error when the `deploy:reset_permissions` task is run:

```
sudo: unable to execute /bin/chmod: Argument list too long
```

![16-22-37 cap -bash 316x80-fwhfl](https://cloud.githubusercontent.com/assets/129031/18689394/87eb5e64-7f4e-11e6-99d2-7a61f2250ace.png)

The `pub/media` directory contains 6492 files: 

![current ssh www-prod questmarkflooring com 316x80-sbe5o](https://cloud.githubusercontent.com/assets/129031/18689462/d3d352e6-7f4e-11e6-8859-80cd374056a9.png)

See this article for context on the error: http://msyk.es/blog/linux-commands-argument-list-too-long/

**Comment by danslo** [comment]
I guess we should just use an `-exec` on the find, instead of using xargs.

**Comment by hostep** [comment]
If I read that article correct, it says the problem is actually in the `-exec` part and the fix is to use `xargs`.
Which makes sense to me.

Now, I searched a little bit further, and somebody mentions this is due to the `sudo` part:
http://www.linuxquestions.org/questions/linux-newbie-8/unable-to-execute-bin-chmod-argument-list-too-long-908143/
Maybe that will solve it?

We never ran into this issue with our Fabric scripts (using xargs), but never use `sudo` and our `pub` directory for a specific project contains for example 24041 files ...

**Comment by davidalger** [comment]
The command in the screenshot isn't something implemented by the capistrano-magento2 gem, so I can't really resolve the issue myself…you'll have to fix this in your custom cap config files on the project.

The permissions related command capistrano-magento2 runs is named `magento:setup:permissions` and runs the following:

``` ruby
    desc 'Sets proper permissions on application'
    task :permissions do
      on release_roles :all do
        within release_path do
          execute :find, release_path, '-type d -exec chmod 770 {} +'
          execute :find, release_path, '-type f -exec chmod 660 {} +'
          execute :chmod, '-R g+s', release_path
          execute :chmod, '+x ./bin/magento'
        end
      end
      Rake::Task['magento:setup:permissions'].reenable  ## make task perpetually callable
    end
```

This results in these commands being run on the target in my test run:

```
02:30 magento:setup:permissions
      01 find /sites/m2cap.demo/releases/20160922173645 -type d -exec chmod 770 {} +
    ✔ 01 vagrant@dev-web70 12.496s
      02 find /sites/m2cap.demo/releases/20160922173645 -type f -exec chmod 660 {} +
    ✔ 02 vagrant@dev-web70 19.501s
      03 chmod -R g+s /sites/m2cap.demo/releases/20160922173645
    ✔ 03 vagrant@dev-web70 29.857s
      04 chmod +x ./bin/magento
    ✔ 04 vagrant@dev-web70 0.018s
```

As @hostep pointed out, the location of the sudo in your command is likely the culprit in your case, as the issue is found in how many arguments sudo can pass on to what it's exec'ing. Doing a find (as I have above), should not run into this issue due to the use of the `{}` in the -exec param (see find man page for details).

**Comment by erikhansen** [comment]
@davidalger Thanks for your help. 

When I submitted this issue, I forgot that a while back I setup a custom `:reset_permissions` task for this project (in a custom `tools/cap/lib/capistrano/tasks/deploy.rake` file) that used the `sudo` command when resetting permissions. I did this due to some special circumstances with the environment that are no longer in play. Removing the custom `tools/cap/lib/capistrano/tasks/deploy.rake` file fixed my problem. Closing this issue. Sorry for reporting an issue that I caused. 😬

@hostep Thanks for piping in on this task and for pointing out the "sudo" issue.
