### ISSUE TITLE
Setup:upgrade running multiple times on multi-server enviroment

### ISSUE THREAD

**Issue by KevinMace** [davidalger/capistrano-magento2#33]
We're running a site over multiple servers and when running a deployment that includes any changes to the DB, we were getting errors due to the setup:upgrade running on all the servers and trying to make the the same DB change multiple times.

It would be great if setup:upgrade only ran on the servers with a role of "db", rather than how it is currently configured to run for 'all' roles.

**Comment by hostep** [comment]
Hi Kevin

I don't think that's correct, because the `setup:upgrade` script not only runs database upgrade scripts, but also manipulates the `app/etc/config.php` file. I'm still not sure if this file should be committed in git or should be ignored in git, but for the people who ignore it, it would be a bad idea to only run `setup:upgrade` on a single server and not on the other nodes.

I think in your case, you have issues because the `setup:upgrade` runs almost at the same time on all the nodes so they all think the database upgrade scripts still need to run? If you time the `setup:upgrade` commands so they run in serial instead of in parallel, I think it will solve your problem. (I'm not sure if you can easily make this happen using Capistrano, maybe something like this: http://stackoverflow.com/a/4572938/145829 ?)

I accidentally worked on deploying M2 to multiple servers today for the first time, so maybe this helps:
We have a small script on each of our nodes which the load balancers checks every few seconds by which the load balancer knows if the node should be consider 'healthy' and if that is the case, send traffic to it. So when we deploy, we make sure each server one by one goes down before running `setup:upgrade` so the load balancer no longer sends traffic to it. Then when one server is finished with the `setup:upgrade` (and some other stuff) we mark the node as 'healthy' again and then do the same on the second server, and so on, and so on.

I haven't fully tested this yet and plan to do this tomorrow or Friday, but I think this should work.

I hope this helps somewhat. :)

**Comment by danslo** [comment]
Not sure about the rest of your post, but I'm quite sure that `app/etc/config.php` should be committed to version control.

**Comment by hostep** [comment]
This is a bit off topic, but I just wanted to address @danslo's comment.

The only reason I can think of for committing that file in version control is to be able to disable modules.
We actually tried it for a while by committing the file in version control and it is a hell to use for multiple developers working on different modules on different branches and then trying to merge those together. You _always_ get conflicts, developers then try to merge them without running `setup:upgrade` again and then committing the file, so the file at that point is in an inconsistent state with the codebase, another developer then pulls in those changes, he runs `setup:upgrade`, the file changes, the developer gets confused because he didn't change any code but still that one file is changed, and it's a whole mess. It could be addressed by trying to discipline the developers a bit more, and that's probably the right solution, but I didn't see it happening after seeing constant problems over multiple months.
So we decided to keep it out of version control and everything works just fine, the file gets generated correctly everywhere, on developer machines, on production systems. In your deploy workflow, you'll need to make sure that file is shared between releases though, otherwise you'll get in trouble.
The only downside to this workflow is, that we can't disable a module. But that's no problem because we have a policy that all the modules in the codebase should always be enabled, and if you don't want a module, just remove all the files belonging to that module.
I wished Magento would split up the file in two different parts, one where the sort order of the modules is defined (this is actually causing most of the conflict problems) and another where we can enable/disable modules. We could then ignore the file in which the sort order of the module is defined and only commit the file with the enabled/disabled state of the modules.

Just my 2 cents...

**Comment by KevinMace** [comment]
@hostep thanks for the replies. We do actually keep `app/etc/config.php` in version control so that wouldn't be an issue for us. Although like you have seen yourself, we do sometimes face issues when merging branches

Your idea of running`setup:upgrade`  in series is a good one, i'll give that a try and see how it goes.

**Comment by davidalger** [comment]
@KevinMace Good catch! I've not personally had the chance to deploy to multi-node with Magento 2 yet, so hadn't run into this. :)

@hostep This gem expects the app/etc/config.php to be committed and currently does a check https://github.com/davidalger/capistrano-magento2/blob/master/lib/capistrano/tasks/magento.rake#L129 for the file before it will do a deploy. I think many folks are split on whether or not this file should be committed. In guidance we received from Magento early on they said commit this file since it tracks module state and load order (that was also one of the reasons it was split off of the env.php file which should _not_ be committed in any case). But I found out doing an MECE deployment that their deploy pattern there is to just enable all modules on every deploy, and config.php is part of the shared assets since they mount app/etc/ into the build. 

In the gem the setup:upgrade call specifies --keep-generated, so the only purpose here really is to upgrade the database schemas, not do anything in the local file-system. If the config.php wasn't expected to be committed, I would think it would need to be in the shared dir, which at least in all of my M1 setups, we mount to each device for purposes of sharing both config and media / static-assets, etc.

In cases where setup:upgrade has not yet run and a module version has changed, the site will throw error pages everywhere till the database is updated. Do you run into that with how you're rotating nodes behind the load balancer?

What I really want to do is implement a check to see if any updates are necessary before running setup:upgrade and only put into maintenance mode (it's only down for about 5-10 seconds barring major updates) if updates are really needed. Having the config.php allows for this, since the contents and order should have been determined in dev before the code is deployed to staging / production via capistrano.

**Comment by davidalger** [comment]
@KevinMace My plan for this is to wrap this setup:upgrade call so it only runs on the primary node in the setup role. I might be able to get to this today, and I'll ping back here when I do.

**Comment by davidalger** [comment]
Also FTR, I'm open to changing the expectation regarding the config.php file being committed if there are others who wish to not have it committed. Could change it to check for the file either being in the shared directory and/or the repo instead of a single check. The reason for the check being there in the first place was to prevent the script from getting to a point where it assumes the application is installed, and then errors out because commands such as the static-content deploy commands aren't available. Thoughts?

**Comment by KevinMace** [comment]
@davidalger Great, I'll keep an eye out for your update.

**Comment by hostep** [comment]
> This gem expects the app/etc/config.php to be committed and currently does a [check](https://github.com/davidalger/capistrano-magento2/blob/master/lib/capistrano/tasks/magento.rake#L129) for the file before it will do a deploy.

Yes good point, if your gem assumes this, then it's probably ok to only run the `setup:upgrade` on one single node.

> In the gem the setup:upgrade call specifies --keep-generated, so the only purpose here really is to upgrade the database schemas, not do anything in the local file-system. If the config.php wasn't expected to be committed, I would think it would need to be in the shared dir, which at least in all of my M1 setups, we mount to each device for purposes of sharing both config and media / static-assets, etc.

I'm pretty sure that calling `setup:upgrade --keep-generated` also juggles the `app/etc/config.php` file around when it isn't up to date.
Good idea for putting that file in the shared dir across the nodes, I'll see with our hosting company if this is a viable solution.

> In cases where setup:upgrade has not yet run and a module version has changed, the site will throw error pages everywhere till the database is updated. Do you run into that with how you're rotating nodes behind the load balancer?

My basic deployment workflow is up and running, but I have yet to test database migrations.
And you are probably right that all those nodes which are up, but haven't been updated yet will throw errors. My hope is that Magento will change its code to stop throwing errors when the code and database aren't in sync (this should only happen in developer mode). I suspect there might be a possibility this will happen in the future according to @alankent's [comment in his latest blogpost](https://alankent.me/2016/10/01/conventions-for-sass-in-magento-2/#comment-3640) (although he might be talking about other steps in the deployment process)?
But this issue might disappear if we put the `app/etc/config.php` file in the shared directory. Thanks again for mentioning this! I didn't think about this.

> What I really want to do is implement a check to see if any updates are necessary before running setup:upgrade and only put into maintenance mode (it's only down for about 5-10 seconds barring major updates) if updates are really needed. Having the config.php allows for this, since the contents and order should have been determined in dev before the code is deployed to staging / production via capistrano.

You can probably use the command `bin/magento setup:db:status` for this, although I'm not quite sure what it will do when the `app/etc/config.php` file isn't up to date yet...

**Comment by davidalger** [comment]
@KevinMace In the commit above I updated the code to only run setup, cache and index commands on the primary host. You can explicitly set a server as primary, otherwise the first server specified in the role configured via `:magento_deploy_setup_role` (defaults to `:all` so it's not dependent on role naming conventions) will be used (see this on how to set a specific server as primary if needed: http://capistranorb.com/documentation/advanced-features/properties/). 

I made other updates for full multi-host deployment scenarios in develop as well, mostly pertaining to similar incorrect usages of the `release_roles :all` loop. :)

If you could take a peek at this and let me know if you think this will solve the issue, I'll tag and push up a new release to ruby gems.

**Comment by davidalger** [comment]
@hostep 

> I'm pretty sure that calling setup:upgrade --keep-generated also jugles the app/etc/config.php file around when it isn't up to date.

Yes, it does. Since the gem assumes the file is in the repository, it's also assuming that that config.php is current for the code being pushed up. Which means theoretically I suppose it could happen where config.php was updated by setup:upgrade on the primary host, resulting in some hosts having different config.php files, were someone to forget to commit it after doing something which altered the load order. I'm not sure immediately how such a scenario could easily be worked around…especially with the goal of not running setup:upgrade at all unless there are db changes.

> I suspect there might be a possibility this will happen in the future according to @alankent's comment in his latest blogpost (although he might be talking about other steps in the deployment process)?

Based on my current experience working towards a usable MECE deployment and talking to Doug at HQ… this is most likely related to being able to deploy static assets and compile DI without having a properly configured env.php file. The deploy routine for MECE currently does both of those while the site is in maintenance mode because they can't be run during the build phase prior to loading the "image" into the deployment servers. This of course results in a 4-5 minute downtime (minimum) each time deployment is made. Thankfully for us, capistrano makes this particular issue rather moot since it's building in a separate release directory and we can run the static asset and DI compile _before_ linking the new build.

> You can probably use the command bin/magento setup:db:status for this…

I may give this a try; forgot about that command!

**Comment by KevinMace** [comment]
@davidalger The changes in your commit look like they should short the issue i'm having with `setup:upgrade`

I'm however unsure if the cache command should only be run on the primary node as the cache directories `var/cache` and `var/page_cache` are not shared, so only the first/primary node will have its cache flushed and subsequent nodes will have invalid caches.

**Comment by davidalger** [comment]
@KevinMace Thanks for the note on the cache setup! I was assuming that if a deploy is multi-node, the cache would be centralized via the use of redis or something, as that is what we do in most (but not all) of our multi-node deploys. Added a setting to allow for both a central / shared cache setup or one such as you describe where cache operations would need to run on each host. In your setup, this means you'd need to include `set :magento_deploy_cache_shared, false` in your `deploy.rb` config.

The work here has been pushed up as v0.5.3, so you should be able to readily use it by updating your gem. :)

**Comment by KevinMace** [comment]
@davidalger Just a small update, I can confirm your updates have fixed the issue I was having in my first post. Feel free to close this ticket if you're happy to. Thank you for your work maintaining this very useful tool.

**Comment by MrDaar** [comment]
Just a random 2 cents.
If your env.php is pulling its values from the environment, and doesn't actually contain any usernames or passwords, would it be a problem to have it in the repo?

**Comment by benyanke** [comment]
At least in my experience, env.php gets overwritten if you try and modify it.

**Comment by cscd98** [comment]
@davidalger How do I set the role - e.g.

set :magento_deploy_setup_role for a specific server?

e.g. 
```
server 'xyz ip', user: 'deploy', roles: %w{app db web}
server 'xyz2 ip', user: 'deploy', roles: %w{app db web}
```
