### ISSUE TITLE
Long-term permissions handling proposal

### ISSUE THREAD

**Issue by davidalger** [davidalger/capistrano-magento2#38]
Current permissions implementation (as of v0.5.4) looks like the following:

```
set :magento_deploy_chmod_d, fetch(:magento_deploy_chmod_d, '2770')
set :magento_deploy_chmod_f, fetch(:magento_deploy_chmod_f, '0660')
set :magento_deploy_chmod_x, fetch(:magento_deploy_chmod_x, ['bin/magento'])
```

``` ruby
execute :find, release_path, "-type d ! -perm #{fetch(:magento_deploy_chmod_d).to_i} -exec chmod #{fetch(:magento_deploy_chmod_d).to_i} {} +"
execute :find, release_path, "-type f ! -perm #{fetch(:magento_deploy_chmod_f).to_i} -exec chmod #{fetch(:magento_deploy_chmod_f).to_i} {} +"

fetch(:magento_deploy_chmod_x).each() do |file|
   execute :chmod, "+x #{release_path}/#{file}"
end
```

ref: https://github.com/davidalger/capistrano-magento2/blob/master/lib/capistrano/tasks/magento.rake#L306-L311

My long-term goal would be to see a better set of default permissions applied by default. It could incorporate things such as read-only access to all php files while allowing write to directories which M2 needs write access to in order to function (think `var` and `pub/media`).

I'm hesitant to do this without putting a lot of research effort into this for a few reasons:
1. The permissions that work well for me might not work for others.
2. Tighter security on the files means less flexibility.
3. Anyone is free to implement their own customized permissions via a custom rake task which executes after the one which runs here:
   
   ``` ruby
   after 'magento:setup:permissions', :my_custom_permissions_task do
     # your custom permissions code
   end
   ```

Any thoughts on how to achieve this and/or make permissions handling more flexible while tightening security of files on the app server(s) is welcome!

**Comment by davidalger** [comment]
The following is an idea proposed by @hostep over here: https://github.com/davidalger/capistrano-magento2/issues/32#issuecomment-251208846. I'm recording it here for reference. 

> @davidalger: no, only Fabric for M2. We used to use Capistrano in our M1 projects, but it was time for something else because we are stuck on version 2 of Capistrano on our workstations since we still have to support M1 projects and we can't install v2 and v3 of Capistrano simultaneously (but that's my own fault, it's the way I set it up 5 years ago without trying to be future-proofed).
> 
> Anyway, regarding file permissions.
> The solution I presented above is also very bad security wise after thinking about it for a while.
> Yesterday, I tried to come up with a workable solution with better security in mind. And I might have found one, but it is very theoretical and hasn't been tested in practice yet.
> 
> If you don't mind, I'll try to explain it, in the hope other people might find it useful or give me some hints about things that are plain wrong in my thinking or maybe suggest some improvements.
> 
> So here we go.
> 
> ### Users
> 
> I see the need for not 2, but **3** different users:
> - the webserver
> - php itself (through php-fpm)
> - the deployer
> 
> I want to use the [principle of least privilege](https://en.wikipedia.org/wiki/Principle_of_least_privilege) where each of these users can only perform what is minimal needed and nothing else.
> - So in the case of the webserver in a M2 environment, it should only have read access to static assets and just hand over php execution to php-fpm which runs as another user.
> - php(-fpm) should only be able to read php scripts, but still have write permissions on specific directories because it needs to be able to write files the users upload through the backend of M2 and it needs write permissions in certain `var/` directories.
> - The deployer has full control over everything.
> 
> ### Permissions
> 
> Since we have 3 users and we have 3 levels in the default file permissions system in a unix environment, this is perfect. (There is another way using [ACL's](https://serversforhackers.com/video/linux-acls) in linux which is even more flexible, but I have no experience with that).
> 
> So I have this mapping in mind:
> 
> | Permission Class | User |
> | --- | --- |
> | owner | deployer |
> | group | php |
> | others | webserver |
> 
> ### Type of files
> - All files except for specific files mentioned below:
> 
> | User | Permissions | Octal |
> | --- | --- | --- |
> | deployer | read + write | 6 |
> | php | read | 4 |
> | webserver | no access | 0 |
> - Files in the `pub` directory, or even more strict, only in the `pub/media` directory:
> 
> | User | Permissions | Octal |
> | --- | --- | --- |
> | deployer | read + write | 6 |
> | php | read + write | 6 |
> | webserver | read | 4 |
> - Files in the `var` directory, or even more strict, only in the `var/cache`, `var/page_cache`, `var/log`, `var/report`, `var/session`, ...
> 
> | User | Permissions | Octal |
> | --- | --- | --- |
> | deployer | read + write | 6 |
> | php | read + write | 6 |
> | webserver | no access | 0 |
> 
> ### Type of directories
> 
> (if a directory has no write access but is executable, then the user is still able to access the files within the directory, but just can't list the contents of the directory)
> - All directories except for specific directories mentioned below:
> 
> | User | Permissions | Octal |
> | --- | --- | --- |
> | deployer | read + write + execute | 7 |
> | php | execute | 1 |
> | webserver | no access | 0 |
> - Directories in the `pub` directory, or even more strict, only in the `pub/media` directory:
> 
> | User | Permissions | Octal |
> | --- | --- | --- |
> | deployer | read + write + execute | 7 |
> | php | read + write + execute | 7 |
> | webserver | execute | 1 |
> 
> => In this case, I would also enable the setuid and setgid bit, so if php creates a new directory, it inherits the owner and group, in this case the octal representation would be 6771
> - Directories in the `var` directory, or even more strict, only in the `var/cache`, `var/page_cache` directories:
> 
> | User | Permissions | Octal |
> | --- | --- | --- |
> | deployer | read + write + execute | 7 |
> | php | read + write + execute | 7 |
> | webserver | no access | 0 |
> 
> ### Warning
> 
> Like I mentioned, this is highly theoretical and hasn't been tested properly in practice.
> I'm far from a security expert, but I do have a keen interest in it.
> I want to test this further, but I'm leaving on big hiking trip next week and won't have time to properly test all this in the very near future.
> 
> I hope this is somewhat useful to someone :)

**Comment by bluec** [comment]
Hi David

First of all, thanks for efforts on capistrano-magento2 - it is really well thought out and fills a desparate need for assisting with M2 deployments.

In terms of file permissions the post from @hostep copied above is very well thought out and a great starting point. However it only really accounts for their own preferences/environment and I think flexibility may be the key because of the vast differences in server environments and requirements. For example, it is very typical to implement different permissions in developer mode vs production mode.

Personally I would run php-fpm as the same group as the web server and therefore prefer permissions something like this:

Deployment user: needs write access to everything, and execute access to bin/magento
Web server group: needs read access to everything, write access to some things, and no execute access
Everyone: needs no access to anything

The deployment user would be in the web server group and using the sticky bit on directories would ensure that any files created by this user inherit the correct group. I think this keeps things pretty secure, especially as it totally removes any access for any user other than the deployment user that is not in the web server group.

Using this, I would change permsisions and ownership as follows:

What | Permissions | Ownership
-----|--------|-------
All directories | 2750 | deployer:webserver
All files | 640 | deployer:webserver
Writable directories | 2770 | deployer:webserver
Writable files | 660 | deployer:webserver
Executable files | 740 | deployer:webserver

The challenge is how to achieve something like this, but also satisfy the needs of @hostep and others, and also provide flexibility so that we can set different permissions for different stages?

I think providing a few extra deployment settings may work:

Settings | Default | What it does
--------|--------|---------
:magento_deploy_chmod_d_default | 2750 | Default permissions applied to all directories in the release path
:magento_deploy_chmod_f_default | 640 | Default permissions applied to all non-executable files in the release path
:magento_deploy_chmod_d_writeable | 2770 | Permissions applied to directories in the release path that need to be writeable by the web server
:magento_deploy_chmod_f_writeable | 660 | Permissions applied to files in the release path that need to be writeable by the web server
:magento_deploy_d_writeable | ['pub/static','pub/media','app/etc'] | List of writable directories in release path (all children of these will also be writeable)
:magento_deploy_f_writeable | [] | List of writable files in release path
:magento_deploy_user | deployuser | User who will be user owner of all files/directories
:magento_deploy_group | deploygroup | Group who will be group owner of files/directories

An approach like this should give quite some flexibility. What do others think?

**Comment by davidalger** [comment]
Closing this for now due to inactivity; don't have availability to do anything with it myself. Also just want to re-iterate, this can be solved in so many different ways, it'd be difficult to come to an all-inclusive approach. Permissions and users/groups (as outlined above) is one way to address, use of ACLs is another, and SELinux policies yet another (arguably most secure) solution.
