### ISSUE TITLE
Purging Varnish after a deployment

### ISSUE THREAD

**Issue by KevinMace** [davidalger/capistrano-magento2#43]
I'm trying to purge varnish during a deployment, i've seen in `magento.rake` the code that purges varnish, but i'm getting an error when it runs.

I've added the following to my production.rb:

``
set :ban_pools, ['default']
``
``
set :varnish_cache_hosts, [first_ip_address', 'second_ip_address']
``

During a deployment I get an error because the Magento vanish.vcl expect the  ``X-Magento-Tags-Pattern header`` which doesn't appear to be set during the purge request.

Is the curl command that attempts to flush varnish passing the appropriate header?

**Comment by davidalger** [comment]
@KevinMace I've held off on documenting that (although we use it on all of our projects at Classy Llama) due to a still open issue in the Magento 2 repo where I've asked them to add support to the VCL for the X-Pool header. We use a custom VCL which contains the changes needed to use this. These changes are here: magento/magento2#4106

Since the settings are not yet documented, I may change them a bit once I do get to document them, and I'm hoping Magento will merge the VCL changes soon so I can finalize this and document it so it's easier to use.

**Comment by davidalger** [comment]
@KevinMace You may also see if configuring Magento to purge varnish when the cache:flush operation is run will suffice for your purposes: http://devdocs.magento.com/guides/v2.0/config-guide/varnish/use-varnish-cache.html#use-varnish-magento-purge
