### ISSUE TITLE
capistrano-pending functionality doesn't work unless db role is defined

### ISSUE THREAD

**Issue by erikhansen** [davidalger/capistrano-magento2#58]
When a `db` role is not defined, the capistrano-pending functionality doesn't work. For example, if you're using a role configuration like this:

```
role :app, %w{
  www-data@example.com
}
```

You'll get output like this:

![18-18-04 new message-ysg1u](https://cloud.githubusercontent.com/assets/129031/22858549/9b4334c4-f086-11e6-86ef-080842eb263f.png)

However if you setup both the app and db roles like this:

```
server 'example.com', user: 'www-data', roles: %w{app db}
```

You'll get output like expected:

![18-21-01 new message-um2om](https://cloud.githubusercontent.com/assets/129031/22858564/e4b36368-f086-11e6-9b04-4ff7963360b1.png)

Forcing users to define a db role doesn't seem like the right approach, so I'll let you take it from here to come up with the proper approach to this bug as I don't have any more time to look into this.

This seems to be a bug caused by the Capistrano `:revision` variable (see [here](https://github.com/davidalger/capistrano-magento2/blob/master/lib/capistrano/tasks/pending.rake#L23)) not being populated unless a `db` role is defined. If you agree that this seems to be a core Capistrano bug, not anything related to this Gem, then you're free to close this issue. We may just want to update [the relevant section](https://github.com/davidalger/capistrano-magento2#pending-changes) of this Gem's readme to alert users of this bug and open an issue on the [Capistrano issues list](https://github.com/capistrano/capistrano/issues).

**Comment by davidalger** [comment]
Very good findings, thanks for sharing! Your notes about it being related to the `:db` role not being defined definitely got me on the right track.

The `capistrano-pending` gem looks to `:capistrano_pending_role` for the role to lookup the current revision on. If that var is unset, it defaults to `:db`. So technically not a bug in this gem, certainly not playing nice in all cases, as it would require configuring that gem as well.

I've made changes in the above commit to remedy the issue. In short, I'm setting that role to match the `:magento_deploy_setup_role` by default, but still allowing it to be overridden.

Now all of this said… I've been refactoring this code some more, as I was unraveling more issues with how the underlying functionality works (this is why back when you initially PR'd it I didn't want it enabled by default…I feared it would work inconsistently). For example:

* If REVISION on the server is ahead of the commit being deployed, nothing is reported as being deployed, and the current implementation actually tells the user that the from and to are the same when they are in-fact, definitively NOT the same.

* Oddities in how the revisions are reported, as the current revision is using the lengthy hash, but the deployed ref is using the symbolic name

* Potential to incorrectly report pending changes on a multiple node deployment

In my refactoring, I'm discovering there really is very little in the 3rd-party gem which is not being done natively, so very well may remove it as a dependency by the time I'm finished ;)

**Comment by erikhansen** [comment]
Thanks for spending the time to make fix those issues.

**Comment by davidalger** [comment]
Deploying to multiple hosts which no current deployment:
![cap -bash bash 182x80 2017-02-24 14-56-49](https://cloud.githubusercontent.com/assets/658281/23320705/7ae5553e-faa1-11e6-89a5-8106410346ee.png)

Deploying even changes to multiple hosts:
![cap -bash bash 182x80 2017-02-24 14-55-48](https://cloud.githubusercontent.com/assets/658281/23320667/59ed1ee8-faa1-11e6-8e43-88fc0162ae41.png)

Deploying a revision behind what's currently deployed:
![cap -bash bash 182x80 2017-02-24 14-57-16](https://cloud.githubusercontent.com/assets/658281/23320716/8a4e33b0-faa1-11e6-908b-cbf3e524ced5.png)

Deploying a revision behind what's currently deployed (on single host to create disparity for future test run):
![cap -bash bash 182x80 2017-02-24 14-57-47](https://cloud.githubusercontent.com/assets/658281/23320745/9cd88008-faa1-11e6-853d-d781703c638b.png)

Deploying to multiple hosts which with divergent revisions:
![cap -bash bash 182x80 2017-02-24 14-58-29](https://cloud.githubusercontent.com/assets/658281/23320797/db2a8ca2-faa1-11e6-8cea-303374b0d1e2.png)

No change deployment with the warning; stopped via 'n' input:
![cap -bash bash 182x80 2017-02-24 14-59-56](https://cloud.githubusercontent.com/assets/658281/23320812/eabe0374-faa1-11e6-9aab-78e649e9cc9d.png)

Test with one host having nothing to deploy (warning should not show, with deployment continuing automatically):
![cap -bash bash 182x80 2017-02-24 15-01-26](https://cloud.githubusercontent.com/assets/658281/23320866/21c9b20a-faa2-11e6-8a35-7db39fbacf5c.png)

No change deployment with warning; proceeding via 'y' input:
![cap -bash bash 182x80 2017-02-24 15-02-19](https://cloud.githubusercontent.com/assets/658281/23320886/4036a7f2-faa2-11e6-9c14-7de4cf593a68.png)

Just a simple `deploy:pending` to check on system works (with no warning since it's not a deploy):
![cap -bash bash 182x80 2017-02-24 15-03-15](https://cloud.githubusercontent.com/assets/658281/23320902/60f9d9aa-faa2-11e6-933b-f31b33ea08a4.png)

Adding the following to project configuration will disable warning that will show on deployments with no pending changes:

```ruby
set :magento_deploy_pending_warn, false
```

There are a couple other default values such as the log format and default role to use set in the defaults.rb as well.

One fringe case which I have not accounted for (and I'm not sure this is a way to account for it very readily): If one is deploying to a different branch than currently deployed, the change log won't show what changes on the current branch are being removed from the server, which could affect deployments where users dynamically change the feature branch being deployed to the same target. An example is the following where the latest commit on the 2.1 branch is currently deployed and cap is asked to deploy from a tag on the 2.0 branch. In that case, the commits from the 2.0 branch will be printed, but the fact that whats currently on the server from the 2.1 branch is ignored:
![cap -bash bash 182x80 2017-02-24 15-09-51](https://cloud.githubusercontent.com/assets/658281/23321065/4ceb18e2-faa3-11e6-8a97-a10c7f39e5e9.png)


This should all be rolled out in the next release.

**Comment by erikhansen** [comment]
Wow, this looks fantastic! Good work on accounting for all of those scenarios.

In regards to the fringe case you mentioned: if the 2nd point in [this issue](https://github.com/davidalger/capistrano-magento2/issues/40) were to be implemented, it seems like it would solve for that use case, as it would warn the user that the deployed branch was being changed and they could do their due diligence to determine the impact of switching branches. I agree with your latest comment on that issue that creating the functionality as a separate Gem might make more sense. My team is managing an M1 project right now and they're frequently deploying different branches and it would be great to be able to pull that functionality into that project.
