### ISSUE TITLE
lib directory additions

### ISSUE THREAD

**Issue by kieronthomas** [davidalger/capistrano-magento2#59]
Hi,

I'm not sure if this is directly an issue for deployment, however it poses a problem.

Currently using the recommended .gitignore from here:
https://github.com/magento/magento2-community-edition/blob/master/.gitignore

The 'lib/' directory is excluded. Some extensions however are placing directories in here, for example Magestore and Magebirdpopup.

Currently I'm forcing a git add on these directories to add them in. Is this the best approach or should it be catered for in deployment?

Kind regards,
Kieron

**Comment by davidalger** [comment]
@kieronthomas This is an issue I would take up with the module vendors if you are concerned about it. In my opinion, they shouldn't be adding code to lib/ as everything in a module should be self-contained.

If the files aren't deployed via the composer install, then you'll need to commit the files so they'll be deployed along with everything else, perhaps adjusting your .gitignore rules to allow those files in lib/ but excluding everything else (or, just force adding them as you are).

HTH

P.S. Since this isn't an issue with the gem itself, I'm going to go ahead and close this. If you need further assistance with figuring out your gitignore etc, I'd suggest taking your questions to one of the stack exchange sites.

Cheers!
