### ISSUE TITLE
Feature request: Don't execute some commands in development environments

### ISSUE THREAD

**Issue by giacmir** [davidalger/capistrano-magento2#6]
It would be nice to have a way to skip `static_content_deploy` and `di_compile` when deploying to a development environment.

**Comment by davidalger** [comment]
@giacmir I did not think of doing that since I only use it to deploy to stage and production sites (both of which I run with MAGE_MODE set to production).

Are those the only commands you'd like to see skipped? I'm thinking I could add a setting `:magento_deploy_production` setting which is `true` by default. This would allow you to disable those commands by setting the flag to false in either `config/deploy.rb` or `config/deploy/<stage_name>.rb`

**Comment by giacmir** [comment]
@davidalger Thanks for your answer. Actually I was thinking of something similar. Some kind of flag that indicates if we are deploying to a production (or production-like) environment or a development one.

In this second case I think that `static_content_deploy` and `di_compile` should be skipped and that `setup:upgrade` should run without the `--keep-generated` flag.

**Comment by giacmir** [comment]
Also I was thinking that in a production environment `composer install` should run with the `--no-dev` flag.

**Comment by davidalger** [comment]
I have heard there are a few issues with --no-dev breaking some things, so I haven't tried it yet for a production install. Have you tried doing that with any success?

**Comment by giacmir** [comment]
No, it was only a conjecture... and I should say, with a point of sadness, that I'm not surprised at all to hear that something used as it should breaks Magento 2... :pensive:
