### ISSUE TITLE
Allow PHP path to be overridden with setting

### ISSUE THREAD

**Issue by JosephLeedy** [davidalger/capistrano-magento2#62]
Our hosting provider has PHP 7.0 installed to a custom path in `/opt`, with a base version of PHP 5.4 in `/usr/bin`. Unfortunately, `/usr/bin/env php` is hard-coded in [magento2.rb](lhttps://github.com/davidalger/capistrano-magento2/blob/master/lib/capistrano/magento2.rb#L10), which picks up PHP 5.4.

Ideally, we would be able to override the PHP path with a setting in deploy.rb or [stage].rb. To that end, I tried adding `SSHKit.config.command_map[:magento]` with the correct path to production.rb. That worked fine for the first occurrence, but not the second one. I also tried to add the setting myself in a fork, but I could get it to output the path correctly. (My Ruby skills are not strong enough to figure why it did not output correctly.)

P.S. Thank you for creating this wonderful tool. Other than the path issue, it works great!

**Comment by davidalger** [comment]
@JosephLeedy You should be able to do this currently by adding the following line to your `.bashrc` file on the remote server:

    export PATH=/opt/php/bin:$PATH

There is also a `:default_env` setting in capistrano which can be used to set the `PATH` for remote commands, but this wouldn't work across the board because of the calls to the `magento_version` method which didn't send env vars with the command (same reason overriding :magento in the command map wouldn't work).

I've fixed the inability to do this in the capistrano configuration, and it should be released in the next update which will be coming fairly soon. You can see the changes I made in commit 69b1c05 above.

Once that is published in a release, one should be able to use a custom PHP binary by adding the following to the project's capistrano configuration:

```ruby
set :default_env, { path: '/opt/php/bin:$PATH' }
```

**Comment by JosephLeedy** [comment]
Thank you for the prompt reply, David. I did try changing the `$PATH` variable in .bashrc, .bash_profile, and .profile on the server and that did not work. I look forward to the release of the update.

**Comment by davidalger** [comment]
@JosephLeedy I tried .bashrc and it worked for me. My guess is your .bashrc is exiting on non-interactive connections, thus evading the new PATH value. If you put it at the top of .bashrc to avoid that, it may work yet. But you're certainly welcome to wait for the new release if you prefer! :)
