### ISSUE TITLE
Add Entire Cli Access 

### ISSUE THREAD

**Issue by osrecio** [davidalger/capistrano-magento2#66]
Would be good have entire access to Command Cli Magento adding something like this in file [magento.rake](https://github.com/davidalger/capistrano-magento2/blob/master/lib/capistrano/tasks/magento.rake) :

```
desc 'Run Magento Cli'
  task :cli, :command do |t,args|
    on primary do
      within release_path do
        execute :magento, args[:command]
      end
    end
  end
```
Usage:
`
cap stage magento:cli['command']
`
E.g:
```
cap production magento:cli['indexer:status']
cap production magento:cli['cache:clean full_page']
```

What do you think?

**Comment by davidalger** [comment]
@osrecio Is the primary use case the desire to specify an argument to the cache:clean command?

There is a whole list of commands from bin/magento which are exposed via individual wrappers. This is a better experience because running `cap -T` can then tell you a full list of commands you can run. They are also documented in the [README](https://github.com/davidalger/capistrano-magento2#magento-specific-tasks)

You may notice that a few of these support specifying an argument (although cache:clean does not currently).

When I created the list, I built it based on my assumptions of which commands would typically need to be run from a control machine via capistrano.

What commands would you like to see added to this list?

**Comment by osrecio** [comment]
@davidalger I know that you have better know-how with `cap -T` to see all commands, etc. 

In this case, IMHO, is the possibility to have all commands of Magento 2 CLI for different purposes or needs that the Deployers can have.

With this funcionality, all developments with Custom commands, can be launched from capistrano. 

What is your point of view? 

P.S: I take this opportunity to congratulate you on the great work you have done.

**Comment by davidalger** [comment]
Closing this for now due to inactivity; don't have availability to do anything with it myself.
