### ISSUE TITLE
After magento 2.1.6 update second static-content:deploy fails

### ISSUE THREAD

**Issue by wintermute-84** [davidalger/capistrano-magento2#69]
Presumably the second run with https: 'on' is failing every time after magento update.

> Successful: 0 files; errors: 7
> ---
> Successful: 6 files; errors: 1
> ---

Please, help, how can I override this task to exclude this behavior.

**Comment by KevinMace** [comment]
I was having a similar issue, it was related to Redis and not an issue with this repository. This is the current issue raised with Magento https://github.com/magento/magento2/issues/9287#issuecomment-299703416

**Comment by davidalger** [comment]
@Dukeofvampires As @KevinMace has noted above, this sounds like it possibly may be due to the issue in Magento causing static-content deployment failure to occur when redis is used as the cache backend. The workaround is to add the following to your `deploy.rb` file as it will disable the "threading" that static-content employs:

    set :magento_deploy_jobs, 1

If you continue to have issues and would like assistance, please provide the full error output. The above message only indicates that the static-content deploy command failed, but doesn't tell me what the errors were (something Magento typically includes in the output).

Closing for now, feel free to re-open if you think there is a bug in this gem. Thanks!
