### ISSUE TITLE
enable modules via deployment?

### ISSUE THREAD

**Issue by chaohe** [davidalger/capistrano-magento2#70]
@davidalger was wondering if you had any plans to incorporate module enabling/disabling into this amazing project? apologize if i'm just not looking in the right place, but i didn't notice any reference to the CLI commands for modules, only printouts of disabled modules in the setup:upgrade task (+1 to #34  by the way)

from my experience, there'd basically be two types of module installations...
1) static-content-less modules - all you'd have to do i believe is run module:enable before setup:upgrade and that would be it.
2) static-content-ful modules - this is where it could get tricky and #34 may come in handy. If static content needs to be generated for the module, then module:enable needs to be run before static content, but then that would mean maintenance mode would be on for the duration of static content. not good.

currently what we are doing is just running the deploy without enabling the module, then going directly into the release folder and running the module-related commands again. very clunky and totally defeats the purpose of the awesomeness of capistrano. any thoughts?

**Comment by danslo** [comment]
You should commit ``app/etc/config.php`` to version control anyway. Not sure if this is something that belongs in deployment.

**Comment by davidalger** [comment]
@chaohe There are no plans for this currently, sorry.

The gem expects the `app/etc/config.php` file to be committed to the project repository, and that file exists solely for the purpose of maintaining module enabled/disabled state.

The reason it spits out a list of disabled modules on deploy is so that you will know if you've forgotten to run module:enable and commit the config.php changes prior to deploy.

A couple benefits of this are:

1. You can deploy with certain modules disabled.

2. We can deploy with near zero downtime, as the db upgrade commands can be run after all the static content generation has occurred.

3. It ensures all servers in deployments to multiple app servers end up with exactly the same code.

> currently what we are doing is just running the deploy without enabling the module, then going directly into the release folder and running the module-related commands again. very clunky and totally defeats the purpose of the awesomeness of capistrano. any thoughts?

Before deploying a module, run the module:enable and commit the changes made to app/etc/config.php. Doing this will ensure the module is enabled on deploy.

You shouldn't have to run anything by hand on the remote server for a deployment, with the exception of having to add an entry to the database for new themes in some cases due to Magento not handling that correctly (see issue #63). We've been using this process for over a year on dozens of M2 sites without any problems. :)

**Comment by chaohe** [comment]
@davidalger thanks for explaining. just so i'm understanding correctly, is this your flow?

1.) run `module:enable` locally, commit all `app/` files plus `config.php` change enabling module
2.) during deployment, `static-content:deploy` is run first, but it will actually generate static content for the new module (even though the module commands like `module:enable` and setup:upgrade haven't been run yet)
3.) the `setup:upgrade` step with `MODULE => 1` in the `config.php` file turns the module on and the new module will work upon deployment completion.

i suppose the 2nd point is where my understanding was lacking?

**Comment by davidalger** [comment]
@chaohe That's pretty much it, yes. If a module is listed in config.php, it's considered enabled. So if it is listed in config.php and the db upgrade commands are run (the gem is actually running setup:db-schema:upgrade and setup:db-data:upgrade vs setup:upgrade) then it is correctly installed / upgraded along with all the other modules.

**Comment by chaohe** [comment]
Confirmed, that worked! Thanks a ton :)
