### ISSUE TITLE
Workaround for broken multi-lingual JS translation deployment in 2.1.3 and newer

### ISSUE THREAD

**Issue by davidalger** [davidalger/capistrano-magento2#72]
See magento/magento2#7862 for core-issue details. This is an implementation of a workaround to allow successful deployment of affected versions.

A loop will be employed so the static content deploy will run separately for each language specified in the `:magento_deploy_languages` setting.

Thanks to @dverkade for bringing this deployment issue to my attention.

**Comment by davidalger** [comment]
## Example Deployment

Deployment of multiple languages should look like the following with the changes in commit 0f7a9a6.

![bash clicolor 1 bash 202x58 2017-06-20 10-32-05](https://user-images.githubusercontent.com/658281/27342673-689694c8-55a6-11e7-9ec0-9ce64b497159.png)

## Testing Instructions

1. Configure deployment to use the feature branch containing the fix for this issue by using the following in your `Gemfile` config:

        gem 'capistrano-magento2', :github => 'davidalger/capistrano-magento2', :branch => 'feature/multi-language-workaround'

2. Update your deployment dependencies

        bundle update

3. Ensure you have multiple languages specified. Example:

        set :magento_deploy_languages, ['en_US', 'en_GB']

4. Run a test deployment using bundler. Example:

        bundle exec cap staging deploy

**Comment by dverkade** [comment]
@davidalger Thanks for fixing this issue and have a workaround for the Magento issue. Can you package this into a new release? This way we can keep using our existing build script / bitbucket pipelines, so we do not have to update that in every project ;-) 

Since this is a workaround for some specific Magento versions. Would it be nice to have a setting forcing this behaviour or do a check on the Magento version to determine if the static content deploy should be run per language or with all languages together?

**Comment by davidalger** [comment]
@dverkade Merge commit for this workaround  is 33e0201. I added a version check so languages are only deployed separately for versions 2.1.3 and later. At which point this is fixed by Magento, an additional maximum version for the workaround can be added.

This has been published in release v0.6.5. Please verify the released version before I close this out. Thanks!

**Comment by avoelkl** [comment]
Just came across this issue, updated capistrano-magento2 and wanted to thank you for this @davidalger. Works for me with version 0.6.6.
