### ISSUE TITLE
multiple calls to maintenance:enable?

### ISSUE THREAD

**Issue by chaohe** [davidalger/capistrano-magento2#75]
maybe i'm missing something because this seems blatant, but it seems like there are multiple calls to enable maintenance mode? 

https://github.com/davidalger/capistrano-magento2/blame/master/lib/capistrano/tasks/deploy.rake#L33

and

https://github.com/davidalger/capistrano-magento2/blame/master/lib/capistrano/tasks/deploy.rake#L38

**Comment by davidalger** [comment]
@chaohe Yes, this is intentional. :) The `invoke 'magento:maintenance:enable'` is enabling maintenance mode on the release being deployed, the subsequent one is explicitly operating on the `current_path` (if it exists) to put the live release into maintenance mode.

The reason this is important is because if the maintenance flag was only set on the currently live release the site would go out of maintenance mode when the symlink for current was updated to point at the new release. This would end up causing a broken site between the symlink change and the cache being flushed when there were changes deployed via setup:upgrade.
