### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by ed007m** [davidalger/capistrano-magento2#80]
I'm trying to execute second deploy of my magneto 2. And I've got this issue:

```
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
** Invoke production 
** Invoke deploy:pending:log (first_time)
** Execute deploy:pending:log
00:00 deploy:pending:log
      01 git fetch origin
      01 fatal: Not a git repository (or any of the parent directories): .git
cap aborted!
Exception while executing as user@test.com: git exit status: 32768
git stdout: Nothing written
git stderr: fatal: Not a git repository (or any of the parent directories): .git
/var/lib/gems/2.1.0/gems/sshkit-1.14.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/var/lib/gems/2.1.0/gems/sshkit-1.14.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
Tasks: TOP => deploy:pending:log
```

Here is my configuration settings:

```
set :application, "test.my"
set :repo_url, "git@gitlab.test.com:ecomitize/test.com.git"
#set :deploy_via, :copy
#set :copy_exclude, [ '.git' ]
set :user, "user"

# Default deploy_to directory is /var/www/my_app_name
set :deploy_to, "/home/user/websites/test.com/public_html"
```

What i'm doing wrong? First initial deploy was success. But all seconds are failure.

**Comment by davidalger** [comment]
@ed007m Where are you running capistrano from? Are you inside a clone of the site's git repository?

What it's doing here is running a `git fetch origin` on the local git checkout in order to spit out a log of changes which will  be deployed during the run for logging / informational purposes. This behavior should only occur if the local env you are running Capistrano from is not a git repository.

If you wish to disable this behavior, simply remove the following line from your `deploy.rb` file:

```ruby
    require 'capistrano/magento2/pending'
```

**Comment by ed007m** [comment]
I'm running capistrano from remote server. On this machine there no site's git repository, but on machine where it is executing it is present. 

However, I've removed line from my file and deploy was success.
So, thanks a lot.
