### ISSUE TITLE
Potentially exposed auth.json

### ISSUE THREAD

**Issue by macieklewkowicz** [davidalger/capistrano-magento2#82]
When using `set :magento_auth_public_key, '<your_public_key_here>'` and `set :magento_auth_private_key, '<your_prviate_key_here>'` to provide credentials, `composer config` is executed and stores them in `./auth.json`. 

https://github.com/davidalger/capistrano-magento2/blob/2a10a675043a6ac23fb9b4e97656c4507a060c47/lib/capistrano/tasks/magento.rake#L109-L113

This might lead to `auth.json` being publicly accessible when Magento is being served from its root folder instead of `./pub`, as the default `.htaccess` does not restrict access to this file.

It might be beneficial to use `COMPOSER_AUTH` instead of `composer config`, as this would not create `auth.json` at all.

**Comment by hostep** [comment]
@macieklewkowicz: that's a really good remark!
But I think this needs to be reported to https://github.com/magento/magento2 or maybe even to https://bugcrowd.com/magento (security issues) so they include it in the default .htaccess file and/or nginx config file (not sure about nginx though, very little experience with that).

**Comment by davidalger** [comment]
@macieklewkowicz Very interesting! All the builds we deploy over here are using pub/ as the root directory, so I didn't stop to consider this.

As @hostep noted, I agree that this should be reported to the Magento2 project as it's pretty common to put auth.json into a project repo given that you need Magento Marketplace credentials to deploy.

I'm going to explore the option of using the COMPOSER_AUTH env var. That would still have the effect of them NOT showing up in the normal capistrano output…so that should work!

**Comment by dverkade** [comment]
This issue has been resolved in Magento 2.0.18, Magento 2.1.12, Magento 2.2.3, so this is no longer an issue for newer Magento releases. See Magento release notes here: https://magento.com/security/patches/magento-2.2.3-2.1.12-and-2.0.18-security-update
APPSEC-1977: Common Server Misconfiguration causes data leak

**Comment by PascalBrouwers** [comment]
Also you could have configured composer to load the auth.json file from **outside** the web folder.
