### ISSUE TITLE
Change "backwards in time" deployments to require confirmation before proceeding

### ISSUE THREAD

**Issue by erikhansen** [davidalger/capistrano-magento2#84]
This Gem has a great feature where you're notified if you're deploying a commit that appears to be behind the currently deployed commit:

![stage ruby -1szev](https://user-images.githubusercontent.com/129031/31352430-5c2bd36a-acf4-11e7-8dfc-b27abd89477b.png)

I suggest that any time it looks like a user is deploying a commit that is "backwards in time", the user is prompted, asking them if they want to continue the deployment.

Here is a scenario in which this would be useful:
* A developer is working on a project where the stage environment is configured to deploy from the `develop` branch.
* A developer wants to deploy an `integration` branch to the stage site in order to test a few features together that the developer does not yet want to merge into develop (for example, an upgrade from one Magento version to the next). The developer run a command like `BRANCH=integration bundle exec cap stage deploy`.
* Over the course of a few days, additional changes are merged into the `integration` branch and the developer deploys those changes to stage. During one of the deployments, the developer forgets to prepend the deployment command with `BRANCH=integration`. This results in stage being deployed from the `develop` branch, which will mean the stage site will in an incorrect state for testing until the developer catches his mistake.

I personally encountered the scenario above twice in the past week. I know that a couple of my colleagues have also wanted a solution to prevent this scenario.

In addition to adding a prompt by default, I think it may be beneficial to add a [Magento Deployment Setting](https://github.com/davidalger/capistrano-magento2#magento-deploy-settings) option to allow this prompt to be disabled.

**Comment by erikhansen** [comment]
@davidalger Let me know if you would accept a PR that implements the change suggested in this issue.

**Comment by davidalger** [comment]
@erikhansen I don't think so. This tool is designed to be run in the context of a CI/CD tool and such functionality would cause problems with said tools. My suggestion would be to use the existing `deploy:pending:log` command to check for this before manually triggering a deployment on projects where this is a risk. If I were going to see something like that as part of this project, it would have to be off by default. That said, since you work where I do :) This isn't something I would want done in our internal use of this tool either as we will be implementing a CI/CD system at some point in the (hopefully near) future and this would setup projects such that they would fail auto-deployment by the CD system.

**Comment by erikhansen** [comment]
@davidalger Ok, I figured that might be your response, but thought I'd check. Thanks for explaining your reasoning.
