### ISSUE TITLE
Provide a configuration flag to disable cache flush during deployment

### ISSUE THREAD

**Issue by dooblem** [davidalger/capistrano-magento2#90]
Hello,

I looked in the code but I did not find any simple/proper way to do that.

We would like to disable cache flush on deployment. (because for some production deployments we do not want to flush the entire magento cache).

Any clue on how to do that? (We may suggest a PR otherwise)

Thanks in advance,
Marc

**Comment by davidalger** [comment]
@dooblem Hey! Sorry about the lack of a reply here…things have been busy and until recently I had little time to throw at improving and/or supporting this gem.

I have no plans to add such a setting as the use case for this would appear to be very minimal and when deploying changes to the application, the cache really should be flushed 9 times out of 10. Failing to do so can cause odd errors and I would rather not introduce the possibility of inconsistency in deployments.

If you would like to suggest a PR that disable the cache flush and/or varnish ban based on an ENV variable being set, I would be open to accepting one. I see it as something which would basically allow one to intentionally disable cache flushing on a single deployment in an ad-hoc fashion (say, if they know the release only changes a couple css lines or static html or something not in the cache):

    NO_CACHE_FLUSH=1 cap production deploy

I'm going to close this out, but do feel free to open a PR. Otherwise you might look into simply redefining the `deploy:published` task in your deployment configuration. Rake tasks do support being overriding, but I don't know off-hand how to do it, so that is an exercise I'll leave for you to pursue. Cheers!
