### ISSUE TITLE
magento:cache:flush not working (as it seems), but no error is returned

### ISSUE THREAD

**Issue by ArvidBaa** [davidalger/capistrano-magento2#94]
Hi!

I have just recently installed Magento 2 and deployed it to an AWS EC2 server connected to an AWS RDS database. When I try to deploy I get no error messages and everything seems just fine. However, after deploy I am unable to access the page and only get database errors.

I have been able to figure out that if I manually access the server using ssh and call `php -f bin/magento -- cache:flush` from the root directory of the project, the page is able to load without database errors.

Why is it that the `magento:cache:flush` call from Capistrano doesn't succeed, and why doesn't it notice and/or display any errors? And most important, what can I do to fix this?

**Comment by ArvidBaa** [comment]
Update:
I have learned a lot since the above error occured.
The error is this:
```
Warning: file_put_contents(/var/www/site-name/releases/20180110095124/var/cache//mage-tags/mage---1a4_CONFIG): failed to open stream: Permission denied in /var/www/site-name/releases/20180110095124/vendor/colinmollenhour/cache-backend-file/File.php on line 663
```

It seems to be some issue with a file from a module from colinmollenhour, but I really wonder if it is not something else entirely. If you look closely, the path that is trying to be accessed has a double `//` just after the cache folder: `/cache//mage-tags/`. Is this really correct?

Anyway, the issue still resolves if I manually access the server and call `php -f bin/magento -- cache:flush`.

**Comment by davidalger** [comment]
@ArvidBaa Hey! Sorry about the lack of a reply here…things have been busy and until recently I had little time to throw at improving and/or supporting this gem.

If you're still running into this, when the output of the command is not showing, make sure the following line (or similar) is not found anywhere in the projects capistrano configuration:

    set :format_options, command_output: :stderr

When that line is present, it quiets normal command output making commands like "cap production magento:cache:status" rather useless since the output goes to stdout which is merely sent to the capistrano.log file instead of output.

As for why the cache:flush isn't succeeding during deployment but it is succeeding when run manually, I would simply guess that the noted permissions error is the underlying cause (I doubt the double-slash has anything to do with it). Might make sure the deployment is being run as the same user that Magento is running as (with php-fpm or mod_php, etc) on the server as that is the user creating those cache files. Alternatively to make sure cache permissions issues don't occur, you might consider using redis as a cache backend (it'll have the added benefit of being faster!).

Since the issue with cache:flush is not one I can control in this gem, I'm going to go ahead and close this out. If you need more assistance working out this issue, perhaps try the Magento forums or the Stack Exchange sites to get some input from others. Cheers!
