### ISSUE TITLE
How to configure capistrano if tools is not under magento root?

### ISSUE THREAD

**Issue by nntoan** [davidalger/capistrano-magento2#99]
Hi,

I'm wondering is there anyway to use this recipe if `tools/` folder is not under magento root dir?

My current project structure on Git is:

```
--- ROOT
     | --- env
     | --- src (Magento 2 root)
     | --- tools
            | --- cap
```

Cheers.

**Comment by JesKingDev** [comment]
+1 for adding support for Magento in a subdirectory of the repo

**Comment by MagePsycho** [comment]
This has to be reported to the Capistrano itself. Nothing to do with the Capistrano-magento2.

**Comment by nntoan** [comment]
@MagePsycho In the tutorial of the owner himself, he does **RECOMMEND** to use his structures, so I think Capistrano has nothing to do with it.

**Comment by davidalger** [comment]
@nntoan Sorry about the delay here. I've been super busy!

The README is written how I've setup and structured my repos and as many others do them. That is also with the _assumption_ that one will use the current/pub/ as the webroot. Since Magento 2 supports having a webroot that is not the top-level directory in the install, that is the best method IMO of limiting what is exposed on the web server.

As @MagePsycho mentioned though, the core of this is built around how Capistrano itself works. I haven't tested it with Magento 2 (but I have done so years back once or twice on Magento 1 sites) you should be able to use the `:repo_tree` directive to have Capistrano deploy a sub-tree from the Git repo: https://capistranorb.com/documentation/getting-started/configuration/
